/* eslint-disable import/prefer-default-export */
export enum Types {
  FETCH_ENTRIES_STARTED = 'FETCH_ENTRIES_STARTED',
  FETCH_ENTRIES_DONE = 'FETCH_ENTRIES_DONE',
  FETCH_ENTRIES_FAILED = 'FETCH_ENTRIES_FAILED',
  HEADER_TITLE_CHANGED = 'HEADER_TITLE_CHANGED',
  FETCH_THUMBNAIL_STARTED = 'FETCH_THUMBNAIL_STARTED',
  FETCH_THUMBNAIL_DONE = 'FETCH_THUMBNAIL_DONE',
  FETCH_THUMBNAIL_FAILED = 'FETCH_THUMBNAIL_FAILED',
}
